vich_uploader:
    db_driver: orm

    mappings:
        images_directory:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'

        #new_directory:
        #    uri_prefix: /uploads
              #  upload_destination: '%kernel.project_dir%/public/uploads/images'





