<?php
namespace App\Form;
use App\Classe\SearchNews;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchNewsType extends AbstractType
{
    //creation du formulaire
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('string', TextType::class, [
                'label' =>false,
                'required' => false,
                'attr' => [
                    'placeholder' => 'Rechercher par mot clé',
                    'class'=>'form-control-sm'
                ]
            ])

            ->add('startCreatedAt', DateType::class, [
                'label' =>'Du',
                'required'=>false,
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd'])
            ->add('endCreatedAt', DateType::class, [
                'label' =>'Au',
                'required'=>false,
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd']);

           /* ->add('submit', SubmitType::class, [
                'label'=>'Filtrer',
                'attr'=>[
                    'class'=>'btn-block btn-info'
                ]

            ]);*/
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SearchNews::class,
            'method'=> 'GET',
            //desactivation de le crsf protection symfony
            'crsf_protection'=>false,
        ]);
    }

    //fonction
    public function getBlockPrefix()
    {
        return ''; //parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}
