<?php
namespace App\Form;
use App\Classe\Search;
use App\Entity\CategoryDonnees;

use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchType extends AbstractType
{
    //creation du formulaire
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('string', TextType::class, [
                'label' =>false,
                'required' => false,
                'attr' => [
                    'placeholder' => 'Votre recherche par mot clé',
                    'class'=>'form-control-sm'
                ]
            ])

            ->add('searchDate', DateType::class, [
                'label' =>'Par date de création',
                'required'=>false,
                'widget' => 'single_text',
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd'
             /*   'placeholder' => [
        'year' => 'Year', 'month' => 'Month', 'day' => 'Day',
    ]*/
            ])

            ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Search::class,
            'method'=> 'GET',
            //desactivation de le crsf protection symfony
            'crsf_protection'=>false,
        ]);
    }

    //fonction
    public function getBlockPrefix()
    {
        return ''; //parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}
